#pragma once

#include "toml_common.h"
#include "toml_value.h"
#include "toml_array.h"
#include "toml_table.h"
#include "toml_table_array.h"
#include "toml_parser.h"
#include "toml_writer.h"

//macro hygiene
#undef TOML_USE_CHAR_8_IF_AVAILABLE
#undef TOML_ASSERT
#undef TOML_STRICT
#undef TOML_CPP_VERSION
#undef TOML_CPP
#undef TOML_PUSH_WARNINGS
#undef TOML_DISABLE_ALL_WARNINGS
#undef TOML_POP_WARNINGS
#undef TOML_INTERFACE
#undef TOML_EMPTY_BASES
#undef TOML_ALWAYS_INLINE
#undef TOML_ALWAYS_INLINE_WHEN_STRICT
#undef TOML_ASSUME
#undef TOML_UNREACHABLE
#undef TOML_NO_DEFAULT_CASE
#undef TOML_CONSTEVAL
#undef TOML_LIKELY
#undef TOML_UNLIKELY
#undef TOML_NO_UNIQUE_ADDRESS
#undef TOML_NODISCARD_CTOR
#undef TOML_STRING_PREFIX
